apiVersion: apps/v1
kind: Deployment
metadata: 
  name: phpinfo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpinfo-label
  template: 
    metadata:
      labels:
        app: phpinfo-label
    spec:
      containers:
        - #son las propiedades del contendor
          image: paaragon/ibm-phpinfo:latest
          name: phpinfo-container
          ports: 
            - 
              containerPort: 8080
              protocol: TCP
  
